### ISSUE TITLE
Meta Issue: Trialing Dagster

### ISSUE THREAD

**Issue by andrewphilipsmith** [Urban-Analytics-Technology-Platform/poppusher#29]
We have agreed to trial [Dagster](https://dagster.io/) to structure the workflow within popgetter. See [meeting notes here](https://hackmd.io/4-rDxn7KTmqIFgeMZcXcOQ)

This issue is to capture all of the different tasks involved in this.

# Exploration

Within that meeting, we committed to trying three use cases for Dagster before committing to migrating all of popgetter to it. These are:

- [x] A pure python based task (example included in #28)
- [x] Something depending on the Geographic Data Science Docker image (See [this example](https://github.com/dabreegster/popgetter/blob/e709e895cc8733177983960f085b180e73d81560/popgetter/assets/us/__init__.py#L198-L211))
- [x] An escape hatch for wrapping some other third-party tasks (using esoteric dependencies). (Likely to be porting the existing england.py code to Dagster, using [Dagster Pipes](https://github.com/dagster-io/dagster/discussions/16319). (See #32).

# Decision

Once completed, we need to agree whether we are content that Dagster offers a good solution to the workflow management need we've identified (both in the HackMD above, and subsequently whilst attempting these three tasks above).

# Subsequent steps

If the choice of Dagster is confirmed, then there are a number of steps we know we will need to undertake. We can record them here for now. Converting them to individual issues and adding more detail can be done once confirmed.

- [ ] Identify examples of best practices (where they exist) for how to use dagster within popgetter (point to existing implementation within popgetter, rather than reinvent the documentation).
- [ ] Create issues for required use-cases where there is no known best practice.
- [ ] Migrate individual countries to Dagster (create a separate issue/PR for each country).
- [ ] Ensure group/prefixes/jobs etc are organised in a way to make useful subsets of the pipeline easily runnable from the commandline (See #20)
- [x] #38
- [ ] Others things...?

**Comment by andrewphilipsmith** [comment]
All of the tasks outlined in the "Subsequent steps" section above now have separate issues or PRs opened to track them.
