### ISSUE TITLE
Meta Issue: Packaging, dependancy management and versioning

### ISSUE THREAD

**Issue by andrewphilipsmith** [Urban-Analytics-Technology-Platform/poppusher#31]
Some of the things we need in the repo setup (potentially split these up into separate issues):

- [ ] pre-commit hooks 
- [ ] robust version number management
- [ ] some degree of enforcing type checking on Python code
- [ ] CI tests
- [ ] etc

A couple of templates that we might draw on:
- REG are establishing this one, which may or may not do everything we need: https://github.com/alan-turing-institute/python-project-template
- Maturin has suggestions for [mixed Rust/Python projects](https://www.maturin.rs/project_layout#mixed-rustpython-project). I've tried using this.
